// Copyright 2019 Ariel H Garcia Traba <cursos.agt@gmail.com>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
int main(void)
{
	printf("############################################################################\n");
	printf("##                                                                        ##\n");
	printf("##      ¿Qué es C?                                                        ##\n");
	printf("##            * Instalación y configuración                               ##\n");
	printf("##            * Errores sintácticos y lógicos                             ##\n");
	printf("##            * Programación secuencial                                   ##\n");
	printf("##            * Estructuras condicionales simples, compuestas y anidadas  ##\n");
	printf("##            * Estructuras repetitivas                                   ##\n");
	printf("##                                                                        ##\n");
	printf("##      Salida por pantalla                                               ##\n");
	printf("##            * Printf                                                    ##\n");
	printf("##                                                                        ##\n");
	printf("##      Entras por teclado                                                ##\n");
	printf("##            * scanf                                                     ##\n");
	printf("##            * gets                                                      ##\n");
	printf("##                                                                        ##\n");
	printf("##      Variables y Constantes                                            ##\n");
	printf("##            * Tipos de variables                                        ##\n");
	printf("##            * Usos                                                      ##\n");
	printf("##                                                                        ##\n");
	printf("##      Condicionales                                                     ##\n");
	printf("##            * if                                                        ##\n");
	printf("##            * else                                                      ##\n");
	printf("##            * else if                                                   ##\n");
	printf("##                                                                        ##\n");
	printf("##      Bucles                                                            ##\n");
	printf("##            * for                                                       ##\n");
	printf("##            * while                                                     ##\n");
	printf("##            * do while                                                  ##\n");
	printf("##            * break                                                     ##\n");
	printf("##            * continue                                                  ##\n");
	printf("##                                                                        ##\n");
	printf("##      Funciones                                                         ##\n");
	printf("##            * void                                                      ##\n");
	printf("##            * Parámetros                                                ##\n");
	printf("##            * Retorno de datos                                          ##\n");
	printf("##                                                                        ##\n");
	printf("##      Memoria y punteros                                                ##\n");
	printf("##                                                                        ##\n");
	printf("##      Arrays                                                            ##\n");
	printf("##                                                                        ##\n");
	printf("##                                                                        ##\n");
	printf("##      GIT Colaborativo -Pair Programming                                ##\n");
	printf("##            * Creando un repositorio con GIT, clonar, crear branches    ##\n");
	printf("##            * push                                                      ##\n");
	printf("##            * pull                                                      ##\n");
	printf("##                                                                        ##\n");
	printf("############################################################################\n");
    printf( "\n\tContinuar: \n");
    getchar();
    system("clear");
	printf ("\n Durante el siglo XX, científicos como Alan Turing y Lorenzo Church fundaron las bases del cómputo, la programación y sus lenguajes. Los lenguajes de programación actuales, a diferencia de los lenguajes humanos tienen una morfología rígida y simplificada con el fin de ejecutar instrucciones específicas en los sistemas de cómputo. ");
	printf ("\n Lenguajes de alto y bajo nivel. ");
	printf ("\n Los lenguajes de bajo nivel constan de un conjunto básico de instrucciones que son ejecutados directamente por la unidad de procesamiento de un sistema de cómputo, tal como es el caso del lenguaje ensamblador. Dichos lenguajes están ligados intrínsecamente al tipo de procesador que los ejecuta y resultan ser muy complicados de elaborar e interpretar por las personas. ");
	printf ("\n Por su parte, los lenguajes de alto nivel son más accesibles para el ser humano e incluso menos dependientes del tipo de hardware, pero deben de ser a su vez traducidos a lenguaje de de bajo nivel. ");
	printf ("\n Lenguajes compilados e interpretados. ");
	printf ("\n Los lenguajes de alto nivel interactúan con los sistema de cómputo de dos formas. ");
	printf ("\n     Mediante un compilador, el cual traduce el código de un programa a lenguaje de bajo nivel, dando por resultado un 'archivo binario' el cual es susceptible de ser ejecutado. ");
	printf ("\n     Mediante un intérprete, el cual ejecuta de inmediato las instrucciones que se ingresan. ");
	printf ("\n Por lo general los lenguajes compilados son más rápidos y consumen menos recursos que los lenguajes interpretados en vista de que el archivo resultante es código de bajo nivel, mientras que los lenguajes interpretados deben seguir un proceso a través de varios niveles de abstracción hasta que las instrucciones son ejecutadas por el sistema. ");
	printf ("\n C es un lenguaje compilado de alto nivel. ");
	printf( "\n\tContinuar: \n");
    getchar();
    system("clear");
	printf ("###########################################################################");
	printf ("* * * * * sinoptico* * * * * ");
	printf ("\n * Programar, manipulacion de datos(objetos) tras su ingreso hasta su salida");
	printf ("\n     Un lenguaje es un conjunto de cadenas de símbolos con los que se pueden crear mensajes. De ese modo los mensajes son transmitidos de un emisor a un receptor. Aún cuando en la naturaleza se pueden identificar ciertos lenguajes, los seres humanos hemos desarrollado lenguajes de diversos tipos y gran complejidad. ");
	printf ("\n     Los lenguajes constan principamente de la gramática, la cual trata sobre la construcción del lenguaje, y la semántica, la cual trata sobre el significado del lenguaje. ");
	printf ("\n        A su vez, la gramática consta de: ");
	printf ("\n             Morfología: cómo se construyen las notaciones (género, tiempos, declinaciones). ");
	printf ("\n            Sintaxis: cómo se deben escribir las notaciones (orden, estructura). ");
	printf ("\n * Nombre, es la referencia de un dato en un tiempo y espàcio");
	printf ("\n     Nombre : en =/= espacios ,  =  tiempo de ejecucion =/= datos");
	printf ("\n     Nombre : en  =  espacios , =/= tiempo de ejecucion =/= datos");
	printf ("\n * Objeto, es su espacio con nombre. Individualidad, con caracteristicas");
	printf ("\n     es su materialización de algo incluso un dato");
	printf ("\n     Posee atributos propios o heredados");
	printf ("\n     Genera acciones propias o heredadas");
	printf ("\n * Funcion-Metodo-Accion-Tarea-Proceso-Verbo");
	printf ("\n     Es el verbo o accion perteneciente a un objeto");
	printf ("\n     Los métodos son bloques de código (o funciones) de una clase que se utilizan para definir el comportamiento de los objetos.");
	printf ("\n * Atributos definen las características propias del objeto y modifican su estado. Son datos asociados a las clases y a los objetos creados a partir de ellas.");
	printf ("\n     De ello, se deducen los dos tipos de atributos o de variables existentes: variables de clase y variables de instancia (objetos).");
	printf ("\n Tanto para acceder a los atributos como para llamar a los métodos se utiliza el método denominado de notación de punto que se basa en escribir el nombre del objeto o de la clase seguido de un punto y el nombre del atributo o del método con los argumentos que procedan: clase.atributo, objeto.atributo, objeto.método([argumentos]).");
	printf ("\n * Instanciar, es crear objetos desde una clase.");
	printf ("\n * Clase, es el razonamiento abstracto de un objeto. Trabajo en distintos capas, en equipo, en grupo, Fron end orientada (al usuario)/ back end (orientada al proceso)");
	printf ("\n * Las clases en este contexto permiten definir los atributos y el comportamiento, mediante métodos, de los objetos de un programa. Una clase es una especie de plantilla o prototipo que se utiliza para crear instancias individuales del mismo tipo de objeto.");
	printf ("\n * Ambito, es una region en el espacio donde los nombres (cuyos datos busco) son accesibles directamente.(Recordad que puede haber el mismo nombre como atributo como accion y en distintos ambitos");
	printf ("\n * Ambito, es observable por estructuras de tabulacion");
	printf ("\n ");
	printf ("\n * Un espacio con un nombre hereda del Nombre ser la referencia a un dato en un tiempo y espàcio.");
	printf ("\n     Si en el espacio nombrado su dato No cambia durante el tiempo de ejecucion se denomina * constante (constantes, tuple etc)");
	printf ("\n     Si en el espacio nombrado su dato Si cambia durante el tiempo de ejecucion se denomina * variable (variable, lista, diccionario, etc");
	printf ("\n     puede haber muchos espacio nombrado igual en distintos ambitos y sus datos podran ser distintos o no");
	printf ("\n     Mutable: su contenido (o dicho valor) puede cambiarse en tiempo de ejecución.");
	printf ("\n     Inmutable: su contenido (o dicho valor) no puede cambiarse en tiempo de ejecución.\n");
	printf ("\n * Una variable es espacio que tendra un nombre para poder acceder a ella y sus caracteristicas seran dadas por el dato que se incorpore (* tipeado dinamico)");
	printf ("\n * Una variable de clase es compartida por todas las instancias de una clase. Se definen dentro de la clase (después del encabezado de la clase) pero nunca dentro de un método. Este tipo de variables no se utilizan con tanta frecuencia como las variables de instancia.");
	printf ("\n * Una variable de instancia se define dentro de un método y pertenece a un objeto determinado de la clase instanciada. ");
	printf ("\n");
	printf ("\n     Mutable: su contenido (o dicho valor) puede cambiarse en tiempo de ejecución.");
	printf ("\n     Inmutable: su contenido (o dicho valor) no puede cambiarse en tiempo de ejecución.\n");
	printf ("\n");
    printf( "\n\tContinuar: \n");
    getchar();
    system("clear");
	printf ("Características de C.");
	printf ("\n");
	printf ("\n A lo largo de estos cursos se explorarán y aprovecharán las características que hacen de C un lenguaje tan popular y poderoso.");
	printf ("\n Definicion al alcance del alumno  - https://es.wikipedia.org/wiki/C_");
	printf ("\nC es un lenguaje de programación de propósito general originalmente desarrollado por Dennis Ritchie entre 1969 y 1972 en los Laboratorios Bell,1​ como evolución del anterior lenguaje B, a su vez basado en BCPL");
	printf ("\nAl igual que B, es un lenguaje orientado a la implementación de Sistemas operativos, concretamente Unix. C es apreciado por la eficiencia del código que produce y es el lenguaje de programación más popular para crear software de sistemas, aunque también se utiliza para crear aplicaciones.");
	printf ("\nSe trata de un lenguaje de tipos de datos estáticos, débilmente tipificado, de medio nivel, ya que dispone de las estructuras típicas de los lenguajes de alto nivel pero, a su vez, dispone de construcciones del lenguaje que permiten un control a muy bajo nivel. Los compiladores suelen ofrecer extensiones al lenguaje que posibilitan mezclar código en ensamblador con código C o acceder directamente a memoria o dispositivos periféricos.");
	printf ("\nLa primera estandarización del lenguaje C fue en ANSI, con el estándar X3.159-1989. El lenguaje que define este estándar fue conocido vulgarmente como ANSI C. Posteriormente, en 1990, fue ratificado como estándar ISO (ISO/IEC 9899:1990). La adopción de este estándar es muy amplia por lo que, si los programas creados lo siguen, el código es portable entre plataformas y/o arquitecturas. ");
    printf( "\n\tContinuar: \n");
    getchar();
    system("clear");
	printf ("\nPropiedades ");
	printf ("\n    Núcleo del lenguaje simple, con funcionalidades añadidas importantes, como funciones matemáticas y de manejo de archivos, proporcionadas por bibliotecas. ");
	printf ("\n    Es un lenguaje estructurado, i.e. tiene estructuras de control y tipos de datos estructurados definidos por el programador a partir de los tipos atómicos típicos y mediante arreglos, estructuras, uniones y apuntadores, incluidos los apuntadores a función. ");
	printf ("\n    En su primera edición no había advertencias sobre asignar a una variable un valor un tipo distinto. Por lo que había un programa llamado lint que detectaba este tipo de errores. Actualmente los compiladores pueden detectar inconsistencias de tipos y otros errores. ");
	printf ("\n    Usa un lenguaje de preprocesado, el preprocesador de C, para tareas como definir macros e incluir múltiples archivos de código fuente. ");
	printf ("\n    Acceso a memoria de bajo nivel mediante el uso de apuntadores o punteros. ");
	printf ("\n    Manejo de Interrupciones mediante la biblioteca signal. ");
	printf ("\n    Un conjunto reducido de palabras clave. ");
	printf ("\n    El llamado a funciones es por valor. Aunque se pueden pasar apuntadores a variables para hacer llamados por referencia. ");
	printf ("\n    Distintos tipos de almacenamiento que permiten un diseño modular. ");
	printf ("\n    La palabra clave static permite encapsular variables y funciones. ");
	printf ("\n    Las estructuras se declaran mediante la palabra clave struct, implementan el producto cartesiano de tipos también llamados registros. ");
	printf ("\n    Y la unión disyunta, también llamada suma, co-producto o tipos variantes, se declara con la palabra clave union. Las estructuras y uniones permiten la implementación de árboles. ");
	printf ("\n    Lenguaje muy eficiente puesto que es posible utilizar sus características de bajo nivel para realizar implementaciones óptimas. ");
	printf ("\n    Se diseñó como un lenguaje de programación de sistemas portátil. ");
	printf ("\n    Es muy poco lo que requiere uso de ensamblador, lo que permitió portar Unix y otros sistemas operativos a distintos equipos. ");
	printf ("\n    Distingue entre mayúsculas y minúsculas, pero conserva su portabilidad en equipos que manejan caracteres de 6 bits, como las computadoras Cyber de CDC que tenían una palabra de 60 bits, (10 caracteres), porque usan trigráficos para codificar símbolos especiales. ");
	printf ("\n    Su compilador de C se ha portado a casi todos los sistemas conocidos. Porque además de que no se requiere codificar en ensamblador, interactúa con los lenguajes especializados YACC y LEX. también escritos en C como parte de Unix. ");
	printf ("\n    Facilita la programación modular gracias a que cuenta con distintos tipos de almacenamiento de las variables y compilación separada. Además del macro procesador integrado cpp, que permite declarar los encabezados de las funciones y los tipos de datos en archivos con extensión h. En el caso de las bibliotecas del sistema Unix y de C se necesita incluir los prototipos con la macros #include por ejemplo #include <system.h>. Ello únicamente sirve para automatizar la declaración de objetos externos que se usarán en el programa, por lo que es necesario pasar los nombres de las bibliotecas como parámetros del compilador que éste pasa al encadenador (linker loader). ");
	printf ("\n    Precauciones que se debe tener por ser un lenguaje de bajo nivel ");
	printf ("\n    Los programadores novatos deben tener cuidado con la gestión de la memoria, en C el programador ha de reservar y liberar la memoria explícitamente. En otros lenguajes (como BASIC o Matlab) la memoria es gestionada de forma transparente para el programador. Esto alivia la carga de trabajo y evita errores, pero le quita flexibilidad al lenguaje para escribir controladores del hardware. ");
	printf ("\n    Por esta razón es muy importante que los recién iniciados adopten buenas prácticas a la hora de escribir en C y manejar la memoria, como por ejemplo un uso intensivo de indentación y conocer a fondo todo lo que implica el manejo de punteros y direcciones de memoria. ");
	printf ("\n    Recolección de basura nativa, sin embargo se encuentran a tal efecto bibliotecas como la 'libgc' desarrollada por Sun Microsystems, o el Recolector de basura de Boehm. ");
	printf ("\n    Soporte para programación orientada a objetos, aunque la implementación original de C++ fue un preprocesador que traducía código fuente de C++ a C. ");
	printf ("\n    Funciones anidadas, aunque GCC tiene esta característica como extensión. ");
	printf ("\n    Soporte nativo para programación multihilo. Disponible usando librerías como libpthread. ");
	printf ("\n    Aunque la lista de las características útiles de las que carece C es larga, este factor ha sido importante para su aceptación, porque escribir rápidamente nuevos compiladores para nuevas plataformas, mantiene lo que realmente hace el programa bajo el control directo del programador, y permite implementar la solución más natural para cada plataforma. Ésta es la causa de que a menudo C sea más eficiente que otros lenguajes. Típicamente, sólo la programación cuidadosa en lenguaje ensamblador produce un código más rápido, pues da control total sobre la máquina, aunque los avances en los compiladores de C y la complejidad creciente de los microprocesadores modernos han reducido gradualmente esta diferencia. ");
	printf ("Gracias Wikipedia");
    printf( "\n\tContinuar: \n");
    getchar();
    system("clear");
}
